"""Add Login

Revision ID: c56214148639
Revises: 2f5d8ba66efc
Create Date: 2022-02-21 23:15:58.631466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c56214148639'
down_revision = '2f5d8ba66efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login', sa.Column('admin_username', sa.String(length=50), nullable=True))
    op.add_column('login', sa.Column('admin_password', sa.String(length=50), nullable=True))
    op.add_column('login', sa.Column('log_bool', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login', 'log_bool')
    op.drop_column('login', 'admin_password')
    op.drop_column('login', 'admin_username')
    # ### end Alembic commands ###
